@startuml "Практическая работа 2"
title Система учета рабочего времени: диаграмма последовательности
skinparam backgroundcolor AntiqueWhite/Gold
participant Руководитель
participant Задание
participant Исполнитель
participant Таймер
activate Руководитель

Руководитель -> Задание: Описывает задание
activate Задание
Руководитель -> Исполнитель: Выдает задание
deactivate Руководитель
activate Исполнитель
Исполнитель -> Таймер:Включает таймер для отслеживания времени
activate Таймер
Исполнитель -> Задание:Приступает к выполнению
Исполнитель -> Задание:Выполняет задание
deactivate Задание
Исполнитель -> Таймер:Закрепляет время выполнения
deactivate Таймер
Исполнитель -> Руководитель:Сообщает о выполнении задания
deactivate Исполнитель
activate Руководитель
Руководитель -> Задание:Проверка качества выполнения
activate Задание
Задание -> Руководитель:Корректное выполнение задания
Руководитель -> Задание:Принимает задание
deactivate Руководитель
deactivate Задание

@enduml